# Generated by Django 3.0 on 2021-01-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=213)),
                ('is_response', models.BooleanField()),
                ('response', models.CharField(max_length=213)),
                ('frequency', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
