# Generated by Django 3.0 on 2021-01-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_questionresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='frequency',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='is_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='response',
            field=models.CharField(max_length=213, null=True),
        ),
    ]
